### ISSUE TITLE
Hello World - Alex

### ISSUE THREAD

**Issue by laylabmanley** [Boxnet-Media/boxnetjam#1]
To get setup, do something in Godot, and make a PR.

- [x] Clone the repository
- [x] Open repository in Godot
- [x] Create new branch
- [x] Create `/scripts` folder, if it doesn't already exist
- [x] Create a folder in `scripts` called `test`
- [x] Create a script in the `test` folder named `alex.gd`
- [x] Make it do something (like print hello world or something)
- [x] Commit to branch
- [x] Push branch to GitHub
- [x] Create PR from branch
- [x] Move back to `main`

**Comment by AlexBowmanCoding** [comment]
i did your shit
