### ISSUE TITLE
Hello World - Foxy

### ISSUE THREAD

**Issue by laylabmanley** [Boxnet-Media/boxnetjam#4]
To get setup, do something in Godot, and make a PR.

- [x] Clone the repository
- [x] Open repository in Godot
- [x] Create new branch
- [x] Create `/scripts` folder, if it doesn't already exist
- [x] Create a folder in `scripts` called `test`, if it doesn't exist
- [x] Create a script in the `test` folder named `foxy.gd`
- [x] Make it do something (like print hello world or something)
- [x] Commit to branch
- [x] Push branch to GitHub
- [x] Create PR from branch
- [x] Move back to `main`

Make sure PR is associated with this issue!

**Comment by laylabmanley** [comment]
https://desktop.github.com/

**Comment by StarryDraco** [comment]
Gamer
